#include <iostream>

//define function to be called externally
//linker **need** to find matching name in the object
//code generated by NASM
extern "C" long long asm_foo(void);

//There's a small library of useless functions defined in assemby called library.asm and
//a header full of conrrespounding C extern symbols called library.hpp
#include "library.hpp"

int main()
{
	const auto answer = compute_answer();
  std::cout << "42 is " << answer << "\n";
}
