#include <iostream>

//define function to be called externally
//linker **need** to find matching name in the object
//code generated by NASM
extern "C" long long asm_foo(void);

//There's a small library of useless functions defined in assemby called library.asm and
//a header full of conrrespounding C extern symbols called library.hpp
#include "library.hpp"

int main()
{
	const auto four = sum_4_ints(1,1,1,1);

	const auto answer = compute_answer();

	int a = 42, b = 32;
	swap(&a, &b);

	int not_zero = 0;
	increment_pointer_int(&not_zero);


	std::cout << asm_foo() << "\n";
}
